@extends('staff.dashboard.layout.base')
@section('content')
    @inject('injected','App\Custom\Regular')

    <div class="row gy-4">

        <div class="col-lg-12">
            <div class="card">

                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table bordered-table mb-0">
                            <thead>
                            <tr>
                                <th scope="col"> S/L</th>
                                <th scope="col"> ID</th>
                                <th scope="col">CODE</th>
                                <th scope="col">DISCOUNT</th>
                                <th scope="col">TYPE</th>
                                <th scope="col">COUPON END DATE</th>
                                <th scope="col">STATUS</th>
                                <th scope="col">GENERATED BY</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($coupons as $index=> $coupon)
                                <tr>
                                    <td>{{$coupons->firstItem()+$index}}</td>
                                    <td>
                                        {{$coupon->reference}}
                                    </td>
                                    <td>
                                        {{$coupon->code}}
                                    </td>
                                    <td>
                                        @if($coupon->couponType==1)
                                            {{$coupon->discount}}%
                                        @else
                                            {{$coupon->currency}}{{$coupon->discount}}
                                        @endif
                                    </td>

                                    <td>
                                        @if($coupon->couponType==1)
                                            Percentage
                                        @else
                                            Flat
                                        @endif
                                    </td>
                                    <td>
                                        @if($coupon->usageDeadline >0)
                                            {{date('dS F, Y', $coupon->usageDeadline)}}
                                        @else
                                            Not Limited By Date
                                        @endif
                                    </td>
                                    <td>
                                        @switch($coupon->status)
                                            @case(1)
                                                <span class="badge bg-success">Active</span>
                                                @break
                                            @default
                                                <span class="badge bg-danger">Inactive</span>
                                                @break
                                        @endswitch
                                    </td>
                                    <td>
                                        @if($user->id==$store->user)
                                            Store Owner
                                        @else

                                            {{$injected->userById($coupon->generatedBy)->name}}
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <div class="mt-3">
                            {{$coupons->links()}}
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

@endsection
