@extends('dashboard.layout.base')
@section('content')
    @inject('injected','App\Custom\Regular')

    <div class="order-details-area mb-0">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6 col-sm-6">
                    <form class="search-bar d-flex">
                        <i class="ri-search-line"></i>
                        <input class="form-control search" type="search" placeholder="Search" aria-label="Search">
                    </form>
                </div>

                <div class="col-lg-6 col-sm-6">
                    <div class="add-new-orders">
                        <a href="{{route('user.stores.coupons.new')}}" class="new-orders">
                            Add New Coupons
                            <i class="ri-add-circle-line"></i>
                        </a>
                    </div>
                </div>
            </div>

            <div class="latest-transaction-area">
                <div class="table-responsive" data-simplebar>
                    <table class="table align-middle mb-0">
                        <thead>
                        <tr>
                            <th scope="col"> ID</th>
                            <th scope="col">CODE</th>
                            <th scope="col">DISCOUNT</th>
                            <th scope="col">TYPE</th>
                            <th scope="col">COUPON END DATE</th>
                            <th scope="col">STATUS</th>
                            <th scope="col">GENERATED BY</th>
                            <th scope="col">ACTION</th>
                        </tr>
                        </thead>
                        <tbody class="searches">
                            @foreach($coupons as $coupon)
                                <tr>
                                    <td>
                                        {{$coupon->reference}}
                                    </td>
                                    <td>
                                        {{$coupon->code}}
                                    </td>
                                    <td>
                                        @if($coupon->couponType==1)
                                            {{$coupon->discount}}%
                                        @else
                                            {{$coupon->currency}}{{$coupon->discount}}
                                        @endif
                                    </td>

                                    <td>
                                        @if($coupon->couponType==1)
                                            Percentage
                                        @else
                                            Flat
                                        @endif
                                    </td>
                                    <td>
                                        @if($coupon->usageDeadline >0)
                                            {{date('dS F, Y', $coupon->usageDeadline)}}
                                        @else
                                            Not Limited By Date
                                        @endif
                                    </td>
                                    <td>
                                        @switch($coupon->status)
                                            @case(1)
                                                <span class="badge bg-success">Active</span>
                                            @break
                                            @default
                                                <span class="badge bg-danger">Inactive</span>
                                            @break
                                        @endswitch
                                    </td>
                                    <td>
                                        @if($user->id==$store->user)
                                            Store Owner
                                        @else

                                            {{$injected->userById($coupon->generatedBy)->name}}
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        <div class="dropdown">
                                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                                <i class="ri-more-2-fill"></i>
                                            </button>
                                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">

                                                <li>
                                                    <a class="dropdown-item" href="{{route('user.stores.coupons.edit',['id'=>$coupon->reference])}}">
                                                        Edit
                                                        <i class="ri-pencil-line"></i>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a class="dropdown-item" href="{{route('user.stores.coupons.delete',['id'=>$coupon->reference])}}">
                                                        Delete
                                                        <i class="ri-delete-bin-6-line"></i>
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <div class="mt-3">
                        {{$coupons->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
